stages:
  - test
  - publish

include:
  project: mattermost/ci/mattermost-webapp
  ref: master
  file: private.yml

lint:
  stage: test
  image: mattermost/mattermost-build-webapp:20200829_node-10.22
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/
      - node_modules/mattermost-redux
  before_script:
    - npm ci --cache .npm --prefer-offline && cd node_modules/mattermost-redux && npm i && npm run build && cd -
  script:
    - npm run check

type-check:
  stage: test
  image: mattermost/mattermost-build-webapp:20200829_node-10.22
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/
      - node_modules/mattermost-redux
  before_script:
    - npm ci --cache .npm --prefer-offline && cd node_modules/mattermost-redux && npm i && npm run build && cd -
  script:
    - npm run check-types

i18n-check:
  stage: test
  image: mattermost/mattermost-build-webapp:20200829_node-10.22
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/
      - node_modules/mattermost-redux
  before_script:
    - npm ci --cache .npm --prefer-offline && cd node_modules/mattermost-redux && npm i && npm run build && cd -
  script:
    - cp i18n/en.json /tmp/en.json
    - mkdir -p /tmp/fake-mobile-dir/assets/base/i18n/
    - echo '{}' > /tmp/fake-mobile-dir/assets/base/i18n/en.json

    - npm run mmjstool -- i18n extract-webapp --webapp-dir . --mobile-dir /tmp/fake-mobile-dir
    - diff /tmp/en.json i18n/en.json
    # Address weblate behavior which does not remove whole translation item when translation string is set to empty
    - npm run mmjstool -- i18n clean-empty --webapp-dir . --mobile-dir /tmp/fake-mobile-dir --check

    - rm -rf tmp

test:
  stage: test
  image: mattermost/mattermost-build-webapp:20200829_node-10.22
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/
      - node_modules/mattermost-redux
  before_script:
    - npm ci --cache .npm --prefer-offline && cd node_modules/mattermost-redux && npm i && npm run build && cd -
  script:
    - npm run test-ci
  artifacts:
    paths:
      - build/
    reports:
      junit: build/
    expire_in: 7 days
